### ISSUE TITLE
Repeatable forms and variants

### ISSUE THREAD

**Issue by ottk-zbw** [tritum/repeatable_form_elements#10]
Hi,
In a repeatableContainer with two elements one element should be required only if the other is filled. This normally works well with variants and a formValue condition. In a repeatableContainer formValues are arrays like:
tx_form_formframework[form-ID][repeatableContainer-ID][0][element-ID]
tx_form_formframework[form-ID][repeatableContainer-ID][1][element-ID]

Is there a possibility to refer to  corresponding formValues[] in a variant condition?

**Comment by stanschus** [comment]
Even though it has been 2 years since this was asked, I'll try to answer it or better to give some hints:  
**disclaimer:** I'm really just throwing in some ideas - I didn't test any of my suggestions
repeatable containers (root container excluded) are created  "on the fly" on server side. root container is the reference, therefor every option/property of each element within additional containers are just copies of the original form element within the root repeatable container. 
So you need to hook into this copy process to adjust any variants which are referencing dynamically created form elements within additional containers.
repeatable container identifier are pretty much build like: repeatableContainer-ID.Index.element-ID. 
so a static reference would look like formValues[repeatablecontainer-1.0.text-1] (root container reference) 
first additional container would be: formValues[repeatablecontainer-1.1.text-1]
it's possible to "freely" use a form element's rendering options in the form definition to build some kind of switch, to make sure you keep static references static and dynamic ones dynamic within repeatable containers and to minimize the need to parse every variant option.
### idea 1: 
use the afterBuildingFinished Hook
check if it is in a repeatable container (hook is triggered by every formelement: https://docs.typo3.org/c/typo3/cms-form/main/en-us/D/FrontendRendering/Index.html#afterbuildingfinished)
check if it has a variant, adjust it - you get the idea
file: CopyService.php
```
     foreach ($GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ext/form']['afterBuildingFinished'] ?? [] as $className) {
            $hookObj = GeneralUtility::makeInstance($className);
            if (method_exists($hookObj, 'afterBuildingFinished')) {
                $hookObj->afterBuildingFinished($newFormElement);
            }
        }
```
### idea 2:
use another hook: https://docs.typo3.org/c/typo3/cms-form/main/en-us/D/FrontendRendering/Index.html#afterinitializecurrentpage if it's only a specific form and manipulate the needed element within the repeatable container

Hope that helps, if anybody finds another solution or proves my ideas work, it would be nice to heard about it ;)

**Comment by chrosey** [comment]
@stanschus 
Thank you for the in-depth analysis.

I will have a look at whether we can adapt the CopyService accordingly so that the variants are also adopted.

**Comment by chrosey** [comment]
I pushed some changes affecting this issue to the `version/4.x.x`. 
Copying elements will now also get an copied version of their variants.

As this can break any existing forms with variants that should only work on the original, this feature can be disabled by a toggle
`$GLOBALS['TYPO3_CONF_VARS']['SYS']['features']['repeatableFormElements.copyVariants']`

In addition, the behavior can be further adapted with PSR-14 EventListener, which react to the event `CopyVariantEvent`.
