### ISSUE TITLE
repeatable parts missing in $this->finisherContext->getFormValues();

### ISSUE THREAD

**Issue by zabinetta** [tritum/repeatable_form_elements#29]
Hi,
I'm quite stuck maybe because I'm just an integrator, but would you maybe please have a look: the repeatable elements are rendered in the receiver- and sender-mails, but not in Extensions like formlog or form_pdf. 
If I understand it right, these extensions use $this->finisherContext->getFormValues(), so they just get the upper layer of the form.
vgl. [https://github.com/pagemachine/typo3-formlog/blob/master/Classes/Domain/Form/Finishers/LoggerFinisher.php] or [https://github.com/t3brightside/form_pdf/blob/master/Classes/Domain/Finishers/PdfFinisher.php]
In order to get the repeatable element values in the logger or the pdf, what would be the best way? assign  'form' => $formRuntime to a template or could there be another solution?
with the best regards,
Sabine

**Comment by chrosey** [comment]
@zabinetta 
many thanks for your patience in this issue. 

Maybe you can have a look at the finisher class in #44. The required step, that many finishers don't iterate into deeper levels of form values. This is fine, because only when `EXT:repeateable_form_elements` (and maybe some others) is installed, there will be nested values. 

In most cases its required to write a own implementation that will do this step. Maybe we can provide a possibility to do so, when `EXT:form` provides Events or Hooks for extending and providing form values for finisher context.

I will close this issue, as it is out of scope for this extension to handle such usages.
